# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1461/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1461/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sergio/code/kdtree-rag

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sergio/code/kdtree-rag

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1461/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1461/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergio/code/kdtree-rag/CMakeFiles /home/sergio/code/kdtree-rag//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergio/code/kdtree-rag/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named llama_client

# Build rule for target.
llama_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llama_client
.PHONY : llama_client

# fast build rule for target.
llama_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_client.dir/build.make CMakeFiles/llama_client.dir/build
.PHONY : llama_client/fast

#=============================================================================
# Target rules for targets named llama_wikihow

# Build rule for target.
llama_wikihow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llama_wikihow
.PHONY : llama_wikihow

# fast build rule for target.
llama_wikihow/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_wikihow.dir/build.make CMakeFiles/llama_wikihow.dir/build
.PHONY : llama_wikihow/fast

src/llama_client.o: src/llama_client.cpp.o
.PHONY : src/llama_client.o

# target to build an object file
src/llama_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_client.dir/build.make CMakeFiles/llama_client.dir/src/llama_client.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_wikihow.dir/build.make CMakeFiles/llama_wikihow.dir/src/llama_client.cpp.o
.PHONY : src/llama_client.cpp.o

src/llama_client.i: src/llama_client.cpp.i
.PHONY : src/llama_client.i

# target to preprocess a source file
src/llama_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_client.dir/build.make CMakeFiles/llama_client.dir/src/llama_client.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_wikihow.dir/build.make CMakeFiles/llama_wikihow.dir/src/llama_client.cpp.i
.PHONY : src/llama_client.cpp.i

src/llama_client.s: src/llama_client.cpp.s
.PHONY : src/llama_client.s

# target to generate assembly for a file
src/llama_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_client.dir/build.make CMakeFiles/llama_client.dir/src/llama_client.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_wikihow.dir/build.make CMakeFiles/llama_wikihow.dir/src/llama_client.cpp.s
.PHONY : src/llama_client.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_client.dir/build.make CMakeFiles/llama_client.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_client.dir/build.make CMakeFiles/llama_client.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_client.dir/build.make CMakeFiles/llama_client.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/wikihow.o: src/wikihow.cpp.o
.PHONY : src/wikihow.o

# target to build an object file
src/wikihow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_wikihow.dir/build.make CMakeFiles/llama_wikihow.dir/src/wikihow.cpp.o
.PHONY : src/wikihow.cpp.o

src/wikihow.i: src/wikihow.cpp.i
.PHONY : src/wikihow.i

# target to preprocess a source file
src/wikihow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_wikihow.dir/build.make CMakeFiles/llama_wikihow.dir/src/wikihow.cpp.i
.PHONY : src/wikihow.cpp.i

src/wikihow.s: src/wikihow.cpp.s
.PHONY : src/wikihow.s

# target to generate assembly for a file
src/wikihow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llama_wikihow.dir/build.make CMakeFiles/llama_wikihow.dir/src/wikihow.cpp.s
.PHONY : src/wikihow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... llama_client"
	@echo "... llama_wikihow"
	@echo "... src/llama_client.o"
	@echo "... src/llama_client.i"
	@echo "... src/llama_client.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/wikihow.o"
	@echo "... src/wikihow.i"
	@echo "... src/wikihow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

